/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct mensagem {
	char m[255];
	int id_mensagem;
	int id_cliente;
};
typedef struct mensagem mensagem;

#define bate_papo 5
#define bate_papo 4

#if defined(__STDC__) || defined(__cplusplus)
#define send_mensagem 1
extern  void * send_mensagem_4(mensagem *, CLIENT *);
extern  void * send_mensagem_4_svc(mensagem *, struct svc_req *);
#define findByMensagem 2
extern  mensagem * findbymensagem_4(int *, CLIENT *);
extern  mensagem * findbymensagem_4_svc(int *, struct svc_req *);
#define cad_cliente 3
extern  int * cad_cliente_4(int *, CLIENT *);
extern  int * cad_cliente_4_svc(int *, struct svc_req *);
extern int bate_papo_4_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send_mensagem 1
extern  void * send_mensagem_4();
extern  void * send_mensagem_4_svc();
#define findByMensagem 2
extern  mensagem * findbymensagem_4();
extern  mensagem * findbymensagem_4_svc();
#define cad_cliente 3
extern  int * cad_cliente_4();
extern  int * cad_cliente_4_svc();
extern int bate_papo_4_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_mensagem (XDR *, mensagem*);

#else /* K&R C */
extern bool_t xdr_mensagem ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAT_H_RPCGEN */
